#!/bin/sh

# swap command and option on daskeyboard
defaults -currentHost write -g com.apple.keyboard.modifiermapping.1241-8211-0  -array \
    '<dict><key>HIDKeyboardModifierMappingDst</key><integer>4</integer><key>HIDKeyboardModifierMappingSrc</key><integer>3</integer></dict>' \
    '<dict><key>HIDKeyboardModifierMappingDst</key><integer>12</integer><key>HIDKeyboardModifierMappingSrc</key><integer>11</integer></dict>' \
    '<dict><key>HIDKeyboardModifierMappingDst</key><integer>3</integer><key>HIDKeyboardModifierMappingSrc</key><integer>4</integer></dict>' \
    '<dict><key>HIDKeyboardModifierMappingDst</key><integer>11</integer><key>HIDKeyboardModifierMappingSrc</key><integer>12</integer></dict>'

# disable capslock on daskeyboard
defaults -currentHost write -g com.apple.keyboard.modifiermapping.1241-8211-0  -array-add \
    '<dict><key>HIDKeyboardModifierMappingDst</key><integer>-1</integer><key>HIDKeyboardModifierMappingSrc</key><integer>0</integer></dict>' \

# disable capslock on macbook internal keyboard
defaults -currentHost write -g com.apple.keyboard.modifiermapping.1452-601-0  -array \
    '<dict><key>HIDKeyboardModifierMappingDst</key><integer>-1</integer><key>HIDKeyboardModifierMappingSrc</key><integer>0</integer></dict>' \

defaults write com.apple.dock autohide-delay -float 0 && killall Dock
defaults write com.apple.dock no-glass -boolean YES && killall Dock

cask_install seil
/Applications/Seil.app/Contents/Library/bin/seil set keycode_capslock 80
/Applications/Seil.app/Contents/Library/bin/seil set enable_capslock 1

cask_install karabiner
ln -sf ~/.dotfiles/karabiner.xml ~/Library/Application\ Support/Karabiner/private.xml
/Applications/Karabiner.app/Contents/Library/bin/karabiner reloadxml
/Applications/Karabiner.app/Contents/Library/bin/karabiner enable private.f192f19_escape
# launch karabiner
# set up hyper key mappings as they occur to me with keyboard maestro
# enable install of apps from anywhere
# 
